### ISSUE TITLE
Extracting RDFa from current HTML document

### ISSUE THREAD

**Issue by william-vw** [rubensworks/rdfa-streaming-parser.js#28]
I'm working on extracting RDF-annotated HTML form data, with RDFa providing the annotations within form elements. The JS code is directly embedded within the HTML document.

For instance:
`<input type='number' min='1' max='10'	step='1' property='fhir:Observation.valueInteger' />`

To that end, I'm using the rdfa-streaming-parser library as follows: `rdfaParser.write($("body").html());` But, this requires manually looking up the input values and inserting them into the extracted RDF (not very difficult, I'm using `rdfjs/N3.js` for this purpose).

I don't think the RDFa parser is currently able to extract RDF from an already-parsed HTML DOM? This could support for these kinds of use cases.

**Comment by rubensworks** [comment]
So if I understand correctly, you would like to pass only a subset of a pre-parsed DOM into the RDFa parser?

If so, I'm not sure if this will work well in all cases. The problem is that RDFa is very context-dependent. So parsing a tag in isolation may have a different meaning that parsing this tag as part of the rest of a document. So I'm a bit hesitant for such functionality.

Parsing the full document and extracting the relevant parts afterwards via N3.js (or even a SPARQL query) feels like a more sustainable solution to me, as you are doing now.

**Comment by william-vw** [comment]
The crux of the use case is extracting RDFa from parsed DOM as opposed to a string. In this use case, the JavaScript is directly embedded in the HTML document, and RDFa needs to be extracted once the user has performed some action.

I believe that extracting RDFa from parsed DOM has two advantages:
(1) no need for parsing the same HTML twice
(2) include input values from form elements, as entered by the user, in the extracted RDF (this is my main interest, really)

RE:
> So parsing a tag in isolation may have a different meaning that parsing this tag as part of the rest of a document

Note that, in this use case, one can just as easily do this using the current solution as well: `rdfaParser.write($("#nestedDiv").html())`

So I don't think this support would necessarily introduce problems there.

**Comment by rubensworks** [comment]
Ok, I understand the use case more clearly now.

Extracting RDFa from a pre-parsed DOM would definitely be possible, but would require quite a bit of implementation effort, so I won't be able to take this up myself.
Concretely, for each node in the DOM, the appropriate listeners of the parser would have to be invoked in the right order: https://github.com/rubensworks/rdfa-streaming-parser.js/blob/master/lib/IHtmlParseListener.ts

Since this repo here focuses on streaming parsing, it might make sense to create this as a separate lib, that just uses rdfa-streaming-parser as a dependency.

**Comment by william-vw** [comment]
Thanks - I may look into it - my current implementation is more of a demo case than an actual system so efficiency is not paramount.

If you like I can create a feature request

**Comment by rubensworks** [comment]
> If you like I can create a feature request

Sure, go ahead :-)
